linters:
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - unused
    - gofmt
  disable:
    - govet

linters-settings:
  errcheck:
    check-type-assertions: true
  gofmt:
    simplify: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
